### ISSUE TITLE
Cant download with cocoapods

### ISSUE THREAD

**Issue by sadiq81** [albert-zhang/AZCenterLabelButton#1]
Installing AZCenterLabelButton (0.1.1)

[!] Error installing AZCenterLabelButton
[!] /usr/bin/git clone https://github.com/albert-zhang/AZCenterLabelButton.git /Users/privat/iOS/HalalGuide/Pods/AZCenterLabelButton --single-branch --depth 1 --branch 0.1.1

Cloning into '/Users/privat/iOS/HalalGuide/Pods/AZCenterLabelButton'...

warning: Could not find remote branch 0.1.1 to clone.

fatal: Remote branch 0.1.1 not found in upstream origin

Unexpected end of command stream
Failed with exit code: 1

**Comment by albert-zhang** [comment]
This is might because I deleted the branch. A new tag is created, it should be working now.
