### ISSUE TITLE
哥，不能用啊。。git配置有问题。。晕

### ISSUE THREAD

**Issue by CaledoniaProject** [albert-zhang/AZCenterLabelButton#2]
没有 0.1.1 这个 branch

**Comment by CaledoniaProject** [comment]
`[!] /usr/bin/git clone https://github.com/albert-zhang/AZCenterLabelButton.git /run/shm/AZCenterLabelButton/Example/Pods/AZCenterLabelButton --single-branch --depth 1 --branch 0.1.1

Cloning into '/run/shm/AZCenterLabelButton/Example/Pods/AZCenterLabelButton'...

warning: Could not find remote branch 0.1.1 to clone.

fatal: Remote branch 0.1.1 not found in upstream origin

Unexpected end of command stream`

**Comment by albert-zhang** [comment]
Please don't 晕 :)  I have created the tag and it should be working now
